# ============================================

# the location of the remote_theme.
remote_theme: techie-joe/dove

# add jekyll-remote-theme to the plugins list.
plugins:
  - jekyll-remote-theme

# ============================================

title         : Proto
description   : Techie Joe's test site.
# title       : The title of your site
# description : Short description of your site's purpose.

author        : Techie Joe

version       : '0.0.4'
revision      : '2601.4'

baseurl       : '/proto'
base_url      : '/proto'
home_url      : '/proto'

lang          : 'en-US'
theme_color   : '#222'
color_scheme  : light dark

ghost         : bG9jYWxob3N0LHRlY2hpZS1qb2UuZ2l0aHViLmlvLGxvY2FsaG9zdDo0MDAw
# ghost: your-tracking-id
# to track your ThemeJs.

# google_analytics: your-tracking-id
# to track your website using Google Analytics.

# cloudflare_analytics: your-tracking-id
# to track your website using Cloudflare Analytics.

# show_downloads: true
# true or false (unquoted).
# to indicate whether to provide a download URL.

# github:
#   zip_url: http://example.com/download.zip
#   another_url: another_value

sass:
  style: compressed

# exclude these from Jekyll production (_site).
exclude:
  - ".editorconfig"
  - ".github"
  - ".gitignore"
  - ".sass-cache"
  - ".jekyll-cache"
  - ".jekyll-metadata"
  - "*.gem"
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - ".bundle"
  - vendor
  - script
  - node_modules
  - package-lock.json
  - package.json
  - gulpfile.js
  - CNAME
  - "*.x"
  - "*.ignore"
  - "*.backup"
  - "*.localhost"