# the location of the remote_theme.
remote_theme: techie-joe/dove
# theme: dove

# add jekyll-remote-theme to the plugins list.
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-remote-theme
  # - jekyll-paginate
  # - jekyll-redirect-from
  # - jekyll-sitemap
  # - jekyll-feed
  # - jemoji

version       : '0.0.3'
revision      : '2601.3'

title         : Proto
description   : Techie Joe's test site.
# title       : The title of your site
# description : Short description of your site's purpose.

author        : Techie Joe
year          : 2025

baseurl       : '/proto'
base_url      : '/proto'
home_url      : '/proto'

lang          : 'en-US'
theme_color   : '#222'
color_scheme  : light dark

ghost         : bG9jYWxob3N0LHRlY2hpZS1qb2UuZ2l0aHViLmlvLGxvY2FsaG9zdDo0MDAw
# ghost: 'your-tracking-id'
# to track your ThemeJs.

# google_analytics: # your Google Analytics tracking ID.
# to track your website using Google Analytics.

# cloudflare_analytics: # your Cloudflare Analytics tracking ID.
# to track your website using Cloudflare Analytics.

# show_downloads: # true or false (unquoted).
# indicate whether to provide a download URL.

# github:
#   zip_url: http://example.com/download.zip
#   another_url: another_value

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default

# exclude these files from Jekyll production site (_site).
exclude:
- ".editorconfig"
- ".github"
- ".gitignore"
- ".sass-cache"
- ".jekyll-cache"
- ".jekyll-metadata"
- "*.gem"
- "*.gemspec"
- Gemfile
- Gemfile.lock
- ".bundle"
- vendor
- script
- node_modules
- package-lock.json
- package.json
- gulpfile.js
- CNAME
- "*.x"
- "*.ignore"
- "*.backup"
- "*.localhost"